name: Codacy Analysis CLI

on: ["push"]

jobs:
  codacy-analysis-cli:
    name: Codacy Analysis CLI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Run Codacy Analysis CLI
        uses: ljmf00/codacy-analysis-cli-action@if-globbing
        with:
          go-version: 1.19.1
          run-gosec: "true"
          run-staticcheck: "true"
          clang-tidy-output: "path/to/output"
          faux-pas-output: "path/to/output"
